<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { createBillingOrder, getBillingAccount, getBillingCatalog, listBillingOrders, payBillingOrder, refundBillingOrder, type BillingAccount, type BillingOrder, type BillingProduct } from '@/api/billing'

const loading = ref(false); const account = ref<BillingAccount | null>(null); const products = ref<BillingProduct[]>([]); const orders = ref<BillingOrder[]>([]); const environment = ref('sandbox')
const load = async () => { loading.value = true; try { const [catalog, current, history] = await Promise.all([getBillingCatalog(), getBillingAccount(), listBillingOrders()]); products.value = catalog.products || []; environment.value = catalog.payment_environment || 'sandbox'; account.value = current; orders.value = history.orders || [] } finally { loading.value = false } }
const purchase = async (product: BillingProduct, priceId: number, amountFen: number) => { await ElMessageBox.confirm(`确认购买「${product.name}」，沙箱标价 ¥${(amountFen/100).toFixed(2)}；升级订单将由服务端按剩余周期计算差价。`, '支付宝沙箱支付', { type:'warning' }); const current = account.value?.subscription; const orderType = product.product_type === 'credit_pack' ? 'credit_pack' : (!current ? 'subscribe' : current.product_key === product.product_key ? 'renew' : 'upgrade'); const created = await createBillingOrder(priceId, orderType); const scene = window.matchMedia('(max-width: 768px)').matches ? 'wap' : 'desktop'; const payment = await payBillingOrder(created.order.order_no, scene); if(payment.payment_environment !== 'sandbox') throw new Error('当前开发版本只允许支付宝沙箱支付'); window.location.assign(payment.redirect_url) }
const refund = async (order: BillingOrder) => { const { value } = await ElMessageBox.prompt('请填写退款原因；已消费额度的订单会转人工审核。','申请退款',{inputPattern:/\S+/,inputErrorMessage:'退款原因不能为空'}); await refundBillingOrder(order.order_no,value); ElMessage.success('退款申请已提交'); await load() }
const formatTime = (value?: number) => value ? new Date(value).toLocaleString('zh-CN',{hour12:false}) : '-'; onMounted(load)
</script>

<template><section class="console-page billing-page" v-loading="loading"><div class="page-header"><div><h1>AI 套餐与额度</h1><p>管理企业 AI 订阅、加量包和支付宝沙箱订单。</p></div></div><el-alert v-if="environment==='sandbox'" title="支付宝沙箱环境：交易仅用于联调，不产生真实扣款，不计入真实营收。" type="warning" :closable="false" show-icon/><div class="summary-strip"><div><span>当前套餐</span><strong>{{ account?.subscription?.product_name || '待开通' }}</strong><small>{{ account?.subscription ? `有效期至 ${formatTime(account.subscription.current_period_end_unix_ms)}` : '请选择套餐' }}</small></div><div><span>可用 AI 额度</span><strong>{{ (account?.available_credits||0).toLocaleString() }}</strong><small>已预占 {{ account?.reserved_credits||0 }}</small></div><div><span>支付环境</span><strong>沙箱</strong><small>仅测试数据</small></div></div><div class="product-grid"><article v-for="product in products" :key="product.id" class="surface-card product-card"><h2>{{ product.name }}</h2><p>{{ product.description }}</p><div v-for="price in product.prices" :key="price.id" class="price-row"><div><strong>{{ price.amount_fen ? `¥${(price.amount_fen/100).toFixed(2)}` : '免费' }}</strong><small>{{ price.billing_term==='yearly'?'按年':price.billing_term==='monthly'?'按月':'一次性' }} · {{ price.included_credits.toLocaleString() }} AI 额度</small></div><el-button v-if="price.amount_fen>0" type="primary" @click="purchase(product,price.id,price.amount_fen)">支付宝沙箱购买</el-button></div></article></div><section class="surface-card orders"><h2>订单记录</h2><el-empty v-if="!orders.length" description="暂无订单"/><div v-for="order in orders" :key="order.order_no" class="order-row"><div><strong>{{ order.product_name }}</strong><span>{{ order.order_no }} · {{ formatTime(order.created_at_unix_ms) }}</span></div><div><el-tag type="warning">沙箱</el-tag><strong>¥{{ (order.amount_fen/100).toFixed(2) }}</strong><el-tag>{{ order.status }}</el-tag><el-button v-if="order.status==='paid'" link type="danger" @click="refund(order)">申请退款</el-button></div></div></section></section></template>

<style scoped>.billing-page{display:grid;gap:20px}.product-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(300px,1fr));gap:16px}.product-card,.orders{padding:24px}.product-card p{min-height:44px;color:var(--el-text-color-secondary)}.price-row,.order-row{display:flex;justify-content:space-between;align-items:center;gap:16px;padding:16px 0;border-top:1px solid var(--el-border-color-lighter)}.price-row>div,.order-row>div:first-child{display:grid;gap:4px}.price-row strong{font-size:24px}.price-row small,.order-row span{color:var(--el-text-color-secondary)}.order-row>div:last-child{display:flex;align-items:center;gap:10px;flex-wrap:wrap}@media(max-width:700px){.price-row,.order-row{align-items:stretch;flex-direction:column}}</style>
