apiVersion: v1
kind: Service
metadata:
  name: logic-grpc-service
  namespace: recruitment
spec:
  type: ClusterIP
  selector:
    app: logic-grpc-service
  ports:
    - name: grpc
      port: 50051
      targetPort: grpc
