name: smart-recruit

services:
  hr-frontend:
    build:
      context: ..
      dockerfile: docker/hr-frontend.Dockerfile
    container_name: recruitment-hr-frontend
    restart: unless-stopped
    ports:
      - "5173:80"

  user-frontend:
    build:
      context: ..
      dockerfile: docker/user-frontend.Dockerfile
    container_name: recruitment-user-frontend
    restart: unless-stopped
    ports:
      - "5174:80"

  interviewer-frontend:
    build:
      context: ..
      dockerfile: docker/interviewer-frontend.Dockerfile
    container_name: recruitment-interviewer-frontend
    restart: unless-stopped
    ports:
      - "5175:80"
