#!/usr/bin/env node

import fs from 'node:fs'
import path from 'node:path'
import process from 'node:process'
import { fileURLToPath } from 'node:url'

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const catalogDir = path.join(root, 'smart-recruit-platform-go', 'i18n', 'catalogs')
const outputPath = path.join(root, 'packages', 'shared', 'src', 'i18n', 'generated.ts')
const locales = ['zh-CN', 'en-US']

const catalogs = Object.fromEntries(locales.map((locale) => {
  const file = path.join(catalogDir, `${locale}.json`)
  return [locale, JSON.parse(fs.readFileSync(file, 'utf8'))]
}))

const keys = Object.keys(catalogs['zh-CN']).sort()
const errors = []
for (const locale of locales) {
  const localeKeys = Object.keys(catalogs[locale]).sort()
  if (JSON.stringify(localeKeys) !== JSON.stringify(keys)) {
    errors.push(`${locale} catalog keys do not match zh-CN`)
  }
}
if (errors.length > 0) {
  process.stderr.write(`${errors.join('\n')}\n`)
  process.exit(1)
}

const generated = `// Generated by scripts/generate-i18n.mjs. Do not edit manually.
export const catalogs = ${JSON.stringify(catalogs, null, 2)} as const

export type MessageKey = keyof typeof catalogs['zh-CN']
`

if (process.argv.includes('--check')) {
  const current = fs.existsSync(outputPath) ? fs.readFileSync(outputPath, 'utf8') : ''
  if (current !== generated) {
    process.stderr.write('generated frontend i18n catalog is stale; run node scripts/generate-i18n.mjs\n')
    process.exit(1)
  }
  process.exit(0)
}

fs.mkdirSync(path.dirname(outputPath), { recursive: true })
fs.writeFileSync(outputPath, generated)
